# Initial setups

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# prompt: generate the code to change the current working directory to main directory

import os
# Check the current working directory
print(os.getcwd())

# Change the current working directory
os.chdir('/content/drive/MyDrive/Complete Machine Learning') # Write the current working directory as parameter

# List contents of the main directory (root directory)
!ls

/content
 Data		 'Data Preprocessing'   Numpy.ipynb
'Data Analysis'  'Gathering the Data'  'Python introduction.ipynb'

In [ ]:
AB_NYC = pd.read_csv('Data/AB_NYC_2019.csv')

# Duplicate Values
* Duplicate data can mislead analysis, introduce bias, and affect machine learning model performance.
* Identifying and handling duplicate values is a crucial step in data cleaning during Exploratory Data Analysis (EDA).
* Keeping duplicate data can lead to incorrect conclusions and distorted results.

## Checking for Duplicate Values
`df.duplicated()` is a Pandas function that checks each row to check for duplicate of a previous row. And Return series of Boolian values  :
> True → row is a duplicate  
> False → row is unique

```
DataFrame.duplicated(subset=None, keep='')
```
**subset** *(default = None, optional)* → Columns to check for duplicates. If None, all columns are used. Example: `subset=['A', 'B']`  
**keep** *(default = 'first', optional)* → Decides which duplicates to mark as False (unique) and which as True (duplicate):

> 'first' → Keep first occurrence, mark others as True.  
> 'last' → Keep last occurrence, mark earlier ones as True.  
> False → Mark all duplicates as True.

In [ ]:
# Rerurn series of boolian values
AB_NYC.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
48901     True
48902     True
48903     True
48904     True
48905     True
Length: 48906, dtype: bool

Use `df.duplicated().sum` to get number of duplicated rows

In [ ]:
# Check for number of duplicate data
AB_NYC.duplicated().sum()

np.int64(11)

In [ ]:
# Finding Duplicates in Multiple Columns
AB_NYC.duplicated(["id", "name"]).sum()

np.int64(11)

In [ ]:
# as 'keep=False' mark all duplicate as true
AB_NYC.duplicated(keep=False).sum()

np.int64(22)

## Removing Duplicates
`df = df.drop_duplicates()` is used to remove duplicate rows from a DataFrame, keeping only the first or last occurrence based on your preference.  
Syntax:  
```
DataFrame.drop_duplicates(subset=None, keep='', inplace=False, ignore_index=False)
```
**subset** *(default = None, optional)* → The column label to check for duplicates.  
**keep** *(default = 'first', optional)* → Which duplicate to keep  
**inplace** *(default = False, optional)* → If `True`, modifies the orignal DataFrame and returns None; if `False`, returns a new DataFrame.  
**ignore_index** *(default = False, optional)* → If `True`, resets the index after removing duplicates.

In [ ]:
# in this case we dont need to change the indexing
df = AB_NYC.drop_duplicates()

In [ ]:
AB_NYC.drop_duplicates(keep='last')

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48901,5441,Central Manhattan/near Broadway,7989,Kate,Manhattan,Hell's Kitchen,40.76076,-73.98867,Private room,85,2,188,23-06-2019,1.50,1,39
48902,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,89,4,167,24-06-2019,1.34,3,314
48903,6021,Wonderful Guest Bedroom in Manhattan for SINGLES,11528,Claudio,Manhattan,Upper West Side,40.79826,-73.96113,Private room,85,2,113,05-07-2019,0.91,1,333
48904,6090,West Village Nest - Superhost,11975,Alina,Manhattan,West Village,40.73530,-74.00525,Entire home/apt,120,90,27,31-10-2018,0.22,1,0
48905,6848,Only 2 stops to Manhattan studio,15991,Allen & Irina,Brooklyn,Williamsburg,40.70837,-73.95352,Entire home/apt,140,2,148,29-06-2019,1.20,1,46

In [ ]:
AB_NYC.drop_duplicates(keep='last',ignore_index=True,inplace=True)
AB_NYC

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,5441,Central Manhattan/near Broadway,7989,Kate,Manhattan,Hell's Kitchen,40.76076,-73.98867,Private room,85,2,188,23-06-2019,1.50,1,39
48891,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,89,4,167,24-06-2019,1.34,3,314
48892,6021,Wonderful Guest Bedroom in Manhattan for SINGLES,11528,Claudio,Manhattan,Upper West Side,40.79826,-73.96113,Private room,85,2,113,05-07-2019,0.91,1,333
48893,6090,West Village Nest - Superhost,11975,Alina,Manhattan,West Village,40.73530,-74.00525,Entire home/apt,120,90,27,31-10-2018,0.22,1,0
48894,6848,Only 2 stops to Manhattan studio,15991,Allen & Irina,Brooklyn,Williamsburg,40.70837,-73.95352,Entire home/apt,140,2,148,29-06-2019,1.20,1,46

## Handling Duplicates in a Specific Column

In [ ]:
# Creating the DataFrame
cities = ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix','Los Angeles', 'Chicago']
rankings = [1, 2, 3, 4, 5,6,7]
scores = [9.8, 9.5, 9.2, 8.7, 8.5, 8.2, 8.1]

data = {'City': cities, 'Ranking': rankings, 'Score': scores}
df = pd.DataFrame(data)
df

          City  Ranking  Score
0     New York        1    9.8
1  Los Angeles        2    9.5
2      Chicago        3    9.2
3      Houston        4    8.7
4      Phoenix        5    8.5
5  Los Angeles        6    8.2
6      Chicago        7    8.1

In [ ]:
# Checking for duplicate in whole DataFrame
df.duplicated().sum()

np.int64(0)

In [ ]:
# Checking for duplicate in "City" Column
df.duplicated(subset=["City"]).sum()

np.int64(2)

In [ ]:
# Removing duplicate while keeping the first occurrence
df.drop_duplicates("City", keep="first")

          City  Ranking  Score
0     New York        1    9.8
1  Los Angeles        2    9.5
2      Chicago        3    9.2
3      Houston        4    8.7
4      Phoenix        5    8.5

In [ ]:
# Removing duplicate while keeping the last occurrence
df.drop_duplicates("City", keep="last")
# It disturb the indexing

          City  Ranking  Score
0     New York        1    9.8
3      Houston        4    8.7
4      Phoenix        5    8.5
5  Los Angeles        6    8.2
6      Chicago        7    8.1

In [ ]:
# Arranged the indexing and Saved in orignal DataFrame
df.drop_duplicates("City", keep='last',ignore_index=True,inplace=True)
df

          City  Ranking  Score
0     New York        1    9.8
1      Houston        4    8.7
2      Phoenix        5    8.5
3  Los Angeles        6    8.2
4      Chicago        7    8.1

# Correction of DataType
When working with datasets, it's common to encounter incorrect data types, which can lead to errors during analysis or modeling. These issues can lead to incorrect calculations, misleading visualizations, or errors in machine learning algorithms.

## 1. Identify Incorrect Data Types
We can check DataType of each column using `df.dtypes` / `df.info()`.

In [ ]:
AB_NYC.dtypes

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group                object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

In [ ]:
AB_NYC.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

## 2. Convert Data Types
After identifying the columns with incorrect types `astype()` function or other specialized conversion functions like `pd.to_datetime()`, `pd.to_numeric`, etc Can be used to correct them.

In [ ]:
AB_NYC['price'] = pd.to_numeric(AB_NYC['price'])

In [ ]:
AB_NYC['last_review'] = pd.to_datetime(AB_NYC['last_review'], errors='coerce')

/tmp/ipython-input-2902645431.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  AB_NYC['last_review'] = pd.to_datetime(AB_NYC['last_review'], errors='coerce')

## 3. Verify the Changes

In [ ]:
AB_NYC.dtypes

id                                         int64
name                                      object
host_id                                    int64
host_name                                 object
neighbourhood_group                       object
neighbourhood                             object
latitude                                 float64
longitude                                float64
room_type                                 object
price                                      int64
minimum_nights                             int64
number_of_reviews                          int64
last_review                       datetime64[ns]
reviews_per_month                        float64
calculated_host_listings_count             int64
availability_365                           int64
dtype: object