#Initial Setup

In [2]:
import numpy as np
import pandas as pd

In [3]:
# prompt: generate the code to change the current working directory to main directory

import os

# Check the current working directory
print(os.getcwd())

# Change the current working directory
os.chdir('/content/drive/MyDrive/Complete Machine Learning') # Write the current working directory as parameter

# Check the current working directory
print(os.getcwd())

# List contents of the main directory (root directory)
!ls

/content
/content/drive/MyDrive/Complete Machine Learning
 Data		      'Gathering the Data'  'Open CV'
'Data Analysis'       'Machine learning'    'Python introduction.ipynb'
'Data Preprocessing'   Numpy.ipynb

In [4]:
Google_PS = pd.read_csv('Data/googleplaystore.csv')
sample = pd.read_csv('Data/Random_Data.csv')
AB_Data = pd.read_csv('Data/AB_NYC_2019.csv')

# Null Values
When working with datasets, it’s common to encounter rows with missing values (null values). Null values can appear in various forms, such as missing ratings, blank cells, or incomplete entries.

Syntax: `Pd.isnull()` / `df.isnull()`  
Parameter : Object to check null values.  
Return : Dataframe of Boolean values.  
Use `df.isnull().sum()` to get numbers of Null Values

## Checking for Null Values

In [5]:
pd.isnull(Google_PS)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,False,False,False,False,False,False,False,False,False,False,False,False,False
10837,False,False,False,False,False,False,False,False,False,False,False,False,False
10838,False,False,True,False,False,False,False,False,False,False,False,False,False
10839,False,False,False,False,False,False,False,False,False,False,False,False,False
10840,False,False,False,False,False,False,False,False,False,False,False,False,False

In [6]:
Google_PS.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

# Null Value Handling

Different Methods of Dealing With Missing Data
1. **Removing Data**  
  * Removing **columns** with too many missing values.  
  * Removing **rows** that contain missing values.
2. **Filling Missing Values (Imputation)**
  * **For numerical data:** Use **mean, median, or mode.**
  * **For categorical data:** Use **mode** or introduce a **new category.**
3. **Advanced Imputation Techniques**
  * **Interpolation** to estimate missing values.
  * **Predictive models** to estimate missing values based on other variables.

# A) Removing Data

### 1) Removing a Column with Too Many Missing Values
If a column has a high percentage of missing values, removing it might be the best choice.
```
AB_Data.drop('COLUMN_NAME', axis=1, inplace=True)
```
inplace : bool, (default = False) If False, return a copy.  
axis=1 (for column)

In [7]:
AB_Data.isnull().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

Insights:
* The last_review and reviews_per_month columns have 10,052 missing values.  
* name and host_name have a few missing values (16 and 21).

In [8]:
AB_Data.shape

(48906, 16)

In [9]:
AB_Data.drop('last_review', axis=1, inplace=True)
AB1 = AB_Data.drop('reviews_per_month', axis=1) # There is no removal of column.(Only copy is created)

In [10]:
display(AB_Data.shape)
display(AB1.shape)

(48906, 15)

(48906, 14)

### 2) Removing Rows with Missing Values
To delete the Null value rows we can use function `dropna()`.

In [11]:
New_PS = Google_PS.dropna() # Making copy of original dataset
AB_Data.dropna(inplace=True) # Changing orignal dataset

In [12]:
display(AB_Data.shape)
display(Google_PS.shape)
display(New_PS.shape)
p=int((10841-9360)*100/10841)
print("There is total",p,"% Loss of data in 'Google_PS' DataSet")

(38832, 15)

(10841, 13)

(9360, 13)

There is total 13 % Loss of data in 'Google_PS' DataSet

Removing rows with missing values can lead to a significant reduction in the size of dataset. As we’ve lost around 13% of our data in above example.

# B) Filling Missing Values (Imputation)
Instead of deleting data, we can replace missing values using **Imputation.**  
**SimpleImputer** is a scikit-learn class which is helpful in handling the missing data in the predictive model dataset. It replaces the NaN values with a specified placeholder.  
It is implemented by the use of the SimpleImputer() method which takes the following arguments :

* **missing_values :** The missing_values placeholder which has to be imputed. By default is NaN  
* **strategy :** The data which will replace the NaN values from the dataset. The strategy argument can take the values – ‘mean'(default), ‘median’, ‘most_frequent’ and ‘constant’.  
* **fill_value :** The constant value to be given to the NaN data using the constant strategy.

Syntax for imputation
```
import numpy as np
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='', fill_value='')
imputer.fit(df.iloc[ : , : ])
df.iloc[ : , : ] = imputer.transform(df.iloc[ : , : ])
```
Syntax for in-build pandas function
```
df[COLUMN_NAME].fillna("N/A or PLACEHOLDER", inplace=True)
```

In [13]:
AB_Data = pd.read_csv('Data/AB_NYC_2019.csv')

### 1) Handling Numerical Data
This is done using imputation techniques, such as:
* **Replace with "N/A" or any placeholder :** Can be anything.
* **Mean :** Good for normally distributed data.
* **Median :** Best for data with outliers.
* **Most Frequent :** Works well for categorical-style numeric data.

Placeholder:
```
df[COLUMN_NAME].fillna("N/A or PLACEHOLDER", inplace=True)
placeholder maybe anything(mean, median, mode, or any specific value, etc.)
```
Mean
```
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
```
Median
```
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
```
Mode/ Most frequent
```
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
```

In [14]:
# Using fillna in-built pandas function
mean = AB_Data['reviews_per_month'].mean()
AB_Data['reviews_per_month'] = AB_Data['reviews_per_month'].fillna(mean)

Using Imputation

In [15]:
#Checking slicing for imputer
sample.iloc[ : , 1:3]

    Age   Salary
0  44.0  72000.0
1  27.0  48000.0
2  30.0  54000.0
3  38.0  61000.0
4  40.0      NaN
5  35.0  58000.0
6   NaN  52000.0
7  48.0  79000.0
8  50.0  83000.0
9  37.0  67000.0

In [16]:
from sklearn.impute import SimpleImputer

# Create an imputer to fill missing values with the most frequent value in each column
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

# Fit the imputer on columns 1 and 2 (index starts from 0)
imputer.fit(sample.iloc[:, 1:3])

# Replacing the missing values
sample.iloc[:, 1:3] = imputer.transform(sample.iloc[:, 1:3])

display(sample)

   Country   Age   Salary Purchased
0   France  44.0  72000.0       Yes
1    Spain  27.0  48000.0       Yes
2      NaN  30.0  54000.0       NaN
3    Spain  38.0  61000.0        No
4  Germany  40.0  48000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  27.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

### 2) Handling Categorical Data
In Categorical Data we can't use mean, median. So we choose the most_frequent as stratergy for filling up the null values.

* **Replace with "N/A" or any placeholder :** Can be domain-specific.

* **Use Mode/most_frequent (default) :** Good for small datasets with repeating categories.

* **Use "Unknown" OR "New_Category" :**  Useful when missing values need to be explicitly labeled.

Placeholders
```
df[COLUMN_NAME].fillna("N/A or placeholder", inplace=True)
```
      placeholder maybe anything(mean, median, mode, specific value, etc.)

Most frequent
```
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
```
Unknown or New category
```
imputer = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value="Unknown")
```

In [17]:
MFV = AB_Data["last_review"].value_counts().index[0] #it take first data from count dataframe
AB_Data["last_review"] = AB_Data["last_review"].fillna(MFV)

Using Imputation

In [18]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

imputer.fit(sample.iloc[:, :])

sample.iloc[:, :] = imputer.transform(sample.iloc[:, :])

Using Unknown

In [19]:
AB_Data['host_name'] = AB_Data["host_name"].fillna("Unknown")

# C) Advanced Imputation
Interpolation is a technique used to estimate and fill missing values in a dataset based on **surrounding data points**.

In [20]:
AB_Data["reviews_per_month"] = AB_Data["reviews_per_month"].interpolate